### ISSUE TITLE
Allow zoom on dark matter graph

### ISSUE THREAD

**Issue by kadrlica** [lsstdarkmatter/dark-matter-graph#1]
Transferring from LSSTDESC/LSSTDarkMatter#9 ...

Is it possible to allow the user to dynamically change the zoom of the dark matter graph? I'm able to change this with the browsers zoom level, but it might be useful to make this part of the webapp. (Also, I expect that the content will only grow, and there may be some reason someone would want to visualize the whole network at once.)

**Comment by yymao** [comment]
@kadrlica now that I think about it, I wonder if there's really a need to reimplement the zoom feature given that the zoom feature is a standard in all modern browsers. 

Do you just want a "fit to window" button for this purpose?

**Comment by kadrlica** [comment]
I don't know how difficult this is, so I'll defer to your experience. My main thought was to have some visual cue that zooming was possible, even if it just used the built in browser functionality (this may be impossible). 

This issue can probably wait until we start seeing the full complexity of the network graphic. I think that if we start to have 50+ measurements then this issue may resurface.

**Comment by yymao** [comment]
In that case, we can simply add text to instruct the user to use the browser built-in zoom function.

**Comment by kadrlica** [comment]
Yes, I think that would be fine for now.

**Comment by yymao** [comment]
As this thing expands, we probably need a "front page" to example what we are doing and provide some instructions to the functionalities of each of these representations.
