### ISSUE TITLE
Display node descriptions

### ISSUE THREAD

**Issue by kadrlica** [lsstdarkmatter/dark-matter-graph#12]
We have talked before about adding "tooltips" with node descriptions. I think it would be best to either display these in a sidebar or only on to display them on click. This would allow the user to continue to mouse-over the network and see connectivity (which is a nice feature of the current implementation).

**Comment by yymao** [comment]
Does the tooltip disappear when mouse hovers out?  Or does it disappear when click happen at a different location?

**Comment by kadrlica** [comment]
I think it disappears when a click happens at a different location (i.e., a different node or white space around nodes). This would be similar to how the matrix boxes stay highlighted on click until a click is made on a non-colored box.

**Comment by yymao** [comment]
Hmm, but in that case, the user won't be able to get a highlighted view without the tooltip's interference, right?  

Current case:
- mouseover: paths are highlighted, tooltip appears
- click: nothing happen visually, but the paths are remembered
- mouseout: paths remain highlighted, tooltip disappears
- click somewhere else: paths dim.

Tooltip on click case:
- mouseover: paths are highlighted
- click: tooltip appears
- mouseout: nothing happen visually (paths remain highlighted; and tooltip remains visible)
- click somewhere else: paths dim, tooltip disappears


I feel the current case is more nature?

**Comment by yymao** [comment]
Another possibility is to display description at a fixed location (say on a side column), not using tooltips.

**Comment by kadrlica** [comment]
I didn't even realize that you could click to keep paths highlighted. Now that I know about it, I find it confusing that I can have multiple paths highlighted at once (the previous one that I clicked on, and the current one that I'm mousing over). 

I like the fixed location idea (i.e. the sidebar suggested in the original comment). I think this could also allow us to display much more information that would be possible with a tooltip.
