### ISSUE TITLE
Increase size of matrix column/row label

### ISSUE THREAD

**Issue by kadrlica** [lsstdarkmatter/dark-matter-graph#14]
The matrix view has the potential to get quite large. It would be awesome if the mouse-over highlighting could also increase the fontsize of the columns/rows label highlighted. I don't know how difficult this is.

**Comment by yymao** [comment]
It's not difficult --- I did try it but it doesn't really look good. I can put that in a branch for people to evaluate.

**Comment by kadrlica** [comment]
Ah interesting. Maybe this could be another "on-click" feature? (Similar to what is suggested for the tooltips in #12.) If/how we want to display descriptions in the matrix view is probably a discussion for another issue.

**Comment by yymao** [comment]
I think we can close this given that we will implement #18. Do you agree, @kadrlica ?

**Comment by kadrlica** [comment]
I agree.
