### ISSUE TITLE
Instructions to click

### ISSUE THREAD

**Issue by kadrlica** [lsstdarkmatter/dark-matter-graph#25]
I think we need to add instructions telling the user to click on a node to see more details.

**Comment by yymao** [comment]
Yep, and the question is how to present the instruction. Maybe put them in a sidebar that always shows up when a user just enter the page?

**Comment by kadrlica** [comment]
That could work nicely. Would it vanish if you clicked on the background, or would it be always present?

**Comment by yymao** [comment]
It would behave like the description sidebar (i.e., being replaced by a new sidebar when a node is clicked, disappearing if when clicking on the background or on the sidebar itself)

**Comment by kadrlica** [comment]
How would the user get the instructions to re-appear once they clicked on the background?

**Comment by yymao** [comment]
Refresh the webpage? I don't know. It's not like we have a super complicated app... 😅  But we could add a link in the footer I guess.

**Comment by kadrlica** [comment]
I agree, and simplicity is one of our strengths! 

I like the new footer with the instructions and relevant links. What about making it a header so that people can see it even if the graphic extends off the bottom of the page?
