### ISSUE TITLE
Add reference links to sidebar text

### ISSUE THREAD

**Issue by kadrlica** [lsstdarkmatter/dark-matter-graph#26]
As part of #19 I've been (sporadically) adding ADS references for different nodes. It would be super cool if we could build ADS links and add them to the sidebar text.

**Comment by yymao** [comment]
should we support arXiv ID and DOI as well?

**Comment by kadrlica** [comment]
Maybe, but I don't think it's critical. I've seen [adstex](https://github.com/yymao/adstex), so I imagine that you already have several tools in place.

**Comment by yymao** [comment]
Right. Another question is whether the references will always be under the "references" key or will there be inline references. The former is obviously easier to implement but I wonder if there's use case for the latter.

**Comment by yymao** [comment]
I'll start with the original request (i.e., only ADS, always under `references` key) since that's the easiest. We can expand this feature if there's demand.

**Comment by kadrlica** [comment]
My plan was to require the developer to be consistent with ADS references always under the `references` key. This would also make it easier to parse the references out of the yaml file for other purposes.
