### ISSUE TITLE
distinguish/visualize the concepts of "paths" and "links" better

### ISSUE THREAD

**Issue by yymao** [lsstdarkmatter/dark-matter-graph#28]
There are two distinct kinds of "objects" that describe how different nodes are connected:

- The first kind we called "paths", as specified in the YMAL data files, provide the connections of among the four categories. Each path connects one node in each category. 
- The second kind we called "links", which are generated from "paths", are the links between nodes that are in adjacent categories. For example, a link connects "SIDM" in Models and "halo density profile" in Probes.

Each "path" would exactly has N-1 "links", where N is the number of categories (currently N=4). Two different paths could share some links

Right now the visualization mostly focus on links rather than paths. Even in the network diagram view, the highlighted paths when mouseover are *all possible paths*, not just the paths we have entered in the YMAL file. 

The question is how to better visualize the "paths" in the matrix view, and also how to distinguish *entered paths* from *all possible paths* in the network diagram view. This is not entirely trivial (both conceptually and technically) so I open this issue to solicit suggestions.

**Comment by kadrlica** [comment]
I didn't realize that the network was showing _all possible paths_. This will be a good issue to track as we use and expand the graphics.

A few conceptual questions that we probably need to think about:
1. Is there a situation where a measurement can connect to a probe, but not all the models that connect to that probe?
2. Is there a conceptual difference between "internal" (probe and measurement) and "external" (model and target) categories? If you click an external node do you want to see only entered paths while for an internal node you want see all possible paths?
