### ISSUE TITLE
Add license

### ISSUE THREAD

**Issue by kadrlica** [lsstdarkmatter/dark-matter-graph#29]
I usually default to the MIT license. @yymao any opinions?

**Comment by yymao** [comment]
yep, that's fine. Note that the license also cover the content (i.e., not just the interface), unless specified. I am fine with making the content also MIT licensed, but just want to point that out.

**Comment by kadrlica** [comment]
I think that's ok.

**Comment by kadrlica** [comment]
Closed by b112efa.
