### ISSUE TITLE
Reference formatting?

### ISSUE THREAD

**Issue by kadrlica** [lsstdarkmatter/dark-matter-graph#35]
How hard is it to format the references as "First Author (Year)" instead of the ADS key?

**Comment by yymao** [comment]
Doing it in the yaml to json conversion step is possible. 

But if that's implemented, there would be more requirements for people who want to run `prepare_data.py`. They'll need to install some packages and also obtain an ADS account to a their API token.

**Comment by kadrlica** [comment]
Maybe it'd be easier to hardcode it in the yaml by changing the references to a key, value pair. Maybe something like:
```
  references:
    - [ADS..Key..YearA, Author (Year)]
    - [ADS..Key..YearA, Author et al. (Year)]
    - ...
```

**Comment by yymao** [comment]
Now that i think about it, given that we have ADS bibcode already, maybe it is easy to do it in the conversion script. Give me a few minutes to confirm.
