### ISSUE TITLE
Text overflowing nodes

### ISSUE THREAD

**Issue by kadrlica** [lsstdarkmatter/dark-matter-graph#50]
This is a browser issue because I have my text size set to "large" rather than "normal", but the text is overflowing the nodes for several probes: "MACHO Mass Function" and "Anomalous Energy Loss" (see attached). @yymao any ideas? Probably not worth fixing, but figured I'd ask.

![image](https://user-images.githubusercontent.com/5605123/36790198-4b2e7302-1c51-11e8-9f8a-051d946528cd.png)

**Comment by yymao** [comment]
@kadrlica should be better now, but let me if the text still overflows on your browser.
